name: PowerShell Lint

on:
  push:
    branches:
      - main
      - master

jobs:
  pwsh-lint:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install PowerShell Module (PSScriptAnalyzer)
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

    - name: Lint PowerShell Script
      shell: pwsh
      run: |
        Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error
